import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./sidebar/page";
import { GlobalContextProvider } from "./Context/store";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Multi-page-forms",
  description: "Generated by Chicodes",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-[#f0f6ff] relative flex flex-col items-center px-2 py-8 md:py-8">
          <main className="p-5 md:rounded md:bg-white md:shadow-3xl w-full flex flex-col md:items-center md:h-[560px] md:w-[860px]  gap-16 md:flex-row md:p-4">
            {/* <div className="flex flex-col md:items-center gap-16 md:flex-row bg-red-500"> */}
              {/* <section class="md:min-h-fit md:bg-white md:rounded-xl md:p-4 h-full md:h-[560px] md:w-[860px] md:shadow-3xl grid grid-rows-4 md:grid-rows-1 md:grid-cols-3" */}
              <Sidebar />
              <GlobalContextProvider>
                {children}
              </GlobalContextProvider>
            {/* </div> */}
          </main>
        </div>
      </body>
    </html>
  );
}
