import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./sidebar/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Multi-page-forms",
  description: "Generated by Chicodes",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-[#f0f6ff] relative flex min-h-screen flex-col items-center justify-between px-2 py-8 md:p-8">
          <main className="block p-5 md:rounded md:bg-white md:shadow-lg w-full md:w-9/12 ">
            <div className="flex flex-col md:items-center gap-16 md:flex-row">
              <Sidebar />
              {children}
            </div>
          </main>
        </div>
      </body>
    </html>
  );
}
