import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./sidebar/page";
import { GlobalContextProvider } from "./Context/store";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Multi-page-forms",
  description: "Generated by Chicodes",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-[#f0f6ff] relative flex flex-col items-center px-2 py-8 md:py-12 min-h[633px] md: h-auto">
          <main className="p-5 md:rounded-xl md:bg-white md:shadow-3xl flex flex-col md:items-center md:justify-center md:h-[560px] md:w-[860px] gap-10 md:flex-row md:p-4 md:min-h-fit">
              <Sidebar />
              <GlobalContextProvider>
                {children}
              </GlobalContextProvider>
            {/* </div> */}
          </main>
        </div>
      </body>
    </html>
  );
}
